export const actionTypes = {
  PROCESS_START: "PROCESS_START",
  PROCESS_FAILURE: "PROCESS_FAILURE",
  FETCH_NOTEBOOKS_SUCCESS: "FETCH_NOTEBOOKS_SUCCESS",
  ADD_NOTEBOOK_SUCCESS: "ADD_NOTEBOOK_SUCCESS",
  UPDATE_NOTEBOOK_NAME_SUCCESS: "UPDATE_NOTEBOOK_NAME_SUCCESS",
  UPDATE_NOTEBOOK_SUCCESS: "UPDATE_NOTEBOOK_SUCCESS",
  DELETE_NOTEBOOK: "DELETE_NOTEBOOK",
};
